### ISSUE TITLE
hammer event data

### ISSUE THREAD

**Issue by nokturnal** [adambabik/angular-hammer-recognizers#1]
Not really an issue, more of a question... Just wondering if there was a snippet explaining how to get the Hammer event data from a hammer event directive (like deltax,touches)     ... Cheers

-- UPDATE --

I am a moron and please ignore this.  It is located in the event.gesture object, exactly where the hammer.js docs said it was...

**Comment by adambabik** [comment]
No problem. Glad you found it :)
