### ISSUE TITLE
Documentation doesn't show Angular integration

### ISSUE THREAD

**Issue by davidgoli** [adambabik/angular-hammer-recognizers#5]
What file needs to be included in the browser in order to use this package?

**Comment by adambabik** [comment]
You need to have three files included:

``` html
<script src="/bower_components/hammerjs/hammer.js"></script>
<script src="/bower_components/angularjs/angular.js"></script>
<script src="/dist/angular-hammer.js"></script>
```

where Hammer and Angular are dependencies. Assuming you have Hammer and Angular already included, you need to add just one file from `dist` directory: `angular-hammer.js` or `angular-hammer.min.js`.
